[package]
name = "Structs"
version = "0.1.0"
authors = ["UmerMIB <47888725+UmerMIB@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
